const data = {
    products: [
        {
            _id: '1',
            name: 'Nike Slim shirt',
            category: 'Shirts',
            image: '/images/p1.jpeg',
            price: 120,
            brand: 'Nike',
            rating:2.5,
            numReviews:10,
            description: 'High quality product',
        },
        {
            _id: '2',
            name: 'Adidas fit shirt',
            category: 'Shirts',
            image: '/images/p2.jpeg',
            price: 100,
            brand: 'Adidas',
            rating:4,
            numReviews:10,
            description: 'High quality product',
        },
        {
            _id: '3',
            name: 'Lacoste Slim shirt',
            category: 'Shirts',
            image: '/images/p3.jpeg',
            price: 120,
            brand: 'Lacoste',
            rating:4.5,
            numReviews:17,
            description: 'High quality product',
        },
        {
            _id: '4',
            name: 'Nike Slim pants',
            category: 'Pants',
            image: '/images/p4.jpeg',
            price: 78,
            brand: 'Nike',
            rating:4.5,
            numReviews:14,
            description: 'High quality product',
        },
        {
            _id: '5',
            name: 'puma slim pants',
            category: 'Pants',
            image: '/images/p5.jpeg',
            price: 120,
            brand: 'puma',
            rating:4.5,
            numReviews:10,
            description: 'High quality product',
        },
        {
            _id: '6',
            name: 'Adidas fit pants',
            category: 'Pants',
            image: '/images/p6.jpeg',
            price: 139,
            brand: 'Adidas',
            rating:4.5,
            numReviews:15,
            description: 'High quality product',
        },
    ],
};

export default data;